apiVersion: v1
kind: Service
metadata:
  name: {{ include "web.name" . }}-svc
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "web.name" . }}
  ports:
      - port: {{ include "web.port" . }}
        protocol: TCP
